### ISSUE TITLE
Don't use floats!

### ISSUE THREAD

**Issue by afk11** [tokenly/counterparty-transaction-composer#1]
I noticed there is use of floats throughout your code. This can cause trouble in languages like PHP, so it's advised to always use integer math (ie, deal in satoshis). 

`self::SATOSHI * $btc` is something to avoid - use \BitWasp\Bitcoin\Amount to whenever you need to accept BTC amounts.

**Comment by deweller** [comment]
I made a conscious decision to use floats in the web APIs for Tokenly tools.  This is because it is easier for the developer to reason about and the Counterparty and Bitcoin server APIs also deal in floats.  That has leaked into other parts of the code and Tokenly components.

That is a good idea to use Amount as a container for values.  Thanks for the tip.  I'm already using a custom `Quantity` class to deal with divisible and indivisible counterparty assets.  I could see extending this (or subclass it from `Amount`) to get rid of the floating point math altogether.

**Comment by afk11** [comment]
I see - just a heads up anyways! Yeah it's funny that Bitcoin Core let it cascade down to the RPC. The first thing it does is convert it as a string to a uint64! 

The Amount class is just for converting BTC to satoshi, and Math wraps GMP for satoshis. I use it at consumer facing endpoints, and convert them back when required, as weird bugs have cropped up otherwise.. Adding large floats on travis (32bit..) caused a bit of bother one day :)
